spring.application.name=ProductApplication
spring.datasource.url=jdbc:mysql://localhost:3306/billSystem
spring.datasource.username=root
spring.datasource.password=Sujit123
spring.jpa.hibernate.ddl-auto=update

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=radhekrishna4351838@gmail.com
spring.mail.password=bjbz xkfr wwvo vsbg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# TWILIO
twilio.account.sid=YOUR_SID
twilio.auth.token=YOUR_TOKEN
twilio.phone.number=+13083368878
twilio.whatsapp.number=whatsapp:+14155238886

